#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const tokensPath = path.join(__dirname, 'clara.tokens.json');
const rawTokens = fs.readFileSync(tokensPath, 'utf8');
const tokens = JSON.parse(rawTokens);

const tokenHash = crypto.createHash('sha256').update(rawTokens).digest('hex').slice(0, 16);
const headerComment = `/* Generated by packages/design-tokens/generate.js - Hash: ${tokenHash} - Version: ${tokens.version} */`;

const toKebabCase = (str) =>
  str
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase();

const capitalize = (str) => str.charAt(0).toUpperCase() + str.slice(1);

const hexToDartColor = (val) => {
  if (!val) return 'const Color(0x00000000)';
  if (typeof val === 'string' && val.startsWith('rgba')) {
    const parts = val.match(/rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d\.]+)\s*\)/);
    if (parts) {
      const a = Math.round(parseFloat(parts[4]) * 255).toString(16).padStart(2, '0').toUpperCase();
      const r = parseInt(parts[1], 10).toString(16).padStart(2, '0').toUpperCase();
      const g = parseInt(parts[2], 10).toString(16).padStart(2, '0').toUpperCase();
      const b = parseInt(parts[3], 10).toString(16).padStart(2, '0').toUpperCase();
      return `Color(0x${a}${r}${g}${b})`;
    }
  }
  const cleanHex = String(val).replace('#', '').toUpperCase();
  if (cleanHex.length === 6) {
    return `Color(0xFF${cleanHex})`;
  } else if (cleanHex.length === 8) {
    return `Color(0x${cleanHex})`;
  }
  return `Color(0xFF${cleanHex})`;
};

// ==========================================
// 1. Generate Web CSS (tokens.css)
// ==========================================
const linesRoot = [];
const linesDark = [];

// --- Global tokens (:root) ---
// Brand Azure
linesRoot.push('  /* Brand Azure */');
for (const [step, val] of Object.entries(tokens.color.brand)) {
  linesRoot.push(`  --clara-brand-${step}: ${val};`);
}
linesRoot.push('');

// Azure Aliases
linesRoot.push('  /* Azure Aliases */');
const azureSource = tokens.color.azure || tokens.color.brand;
for (const [step, val] of Object.entries(azureSource)) {
  linesRoot.push(`  --clara-azure-${step}: ${val};`);
}
linesRoot.push('');

// AI Iris
linesRoot.push('  /* AI Iris */');
for (const [step, val] of Object.entries(tokens.color.iris)) {
  linesRoot.push(`  --clara-iris-${step}: ${val};`);
}
linesRoot.push('');

// Vibrant Clinical Mint
linesRoot.push('  /* Vibrant Clinical Mint */');
for (const [step, val] of Object.entries(tokens.color.mint)) {
  linesRoot.push(`  --clara-mint-${step}: ${val};`);
}
linesRoot.push('');

// Roles
linesRoot.push('  /* Roles */');
for (const [role, val] of Object.entries(tokens.color.role)) {
  linesRoot.push(`  --clara-role-${role}: ${val};`);
  linesRoot.push(`  --role-${role}: ${val};`);
}
linesRoot.push('');

// Ambient Atmosphere (Global defaults)
if (tokens.atmosphere) {
  linesRoot.push('  /* Ambient Atmosphere */');
  for (const [role, val] of Object.entries(tokens.atmosphere)) {
    if (typeof val === 'string') {
      linesRoot.push(`  --clara-atmosphere-${role}: ${val};`);
      linesRoot.push(`  --atmosphere-${role}: ${val};`);
    }
  }
  linesRoot.push('');
}

// Spacing
linesRoot.push('  /* Spacing */');
for (const [step, val] of Object.entries(tokens.spacing)) {
  linesRoot.push(`  --clara-space-${step}: ${val}px;`);
  linesRoot.push(`  --space-${step}: ${val}px;`);
}
linesRoot.push('');

// Radius
linesRoot.push('  /* Radius */');
for (const [key, val] of Object.entries(tokens.radius)) {
  linesRoot.push(`  --clara-radius-${toKebabCase(key)}: ${val}px;`);
  linesRoot.push(`  --radius-${toKebabCase(key)}: ${val}px;`);
}
linesRoot.push('');

// Motion
linesRoot.push('  /* Motion */');
for (const [key, val] of Object.entries(tokens.motion.duration)) {
  linesRoot.push(`  --clara-motion-${key}: ${val}ms;`);
}
for (const [key, val] of Object.entries(tokens.motion.easing)) {
  linesRoot.push(`  --clara-ease-${key}: ${val};`);
}
linesRoot.push('');

// Typography
linesRoot.push('  /* Typography */');
linesRoot.push(`  --clara-font-family: ${tokens.typography.fontFamily};`);
for (const [name, scale] of Object.entries(tokens.typography.scale)) {
  const kebab = toKebabCase(name);
  linesRoot.push(`  --clara-type-${kebab}-size: ${scale.size}px;`);
  linesRoot.push(`  --clara-type-${kebab}-line-height: ${scale.lineHeight}px;`);
  linesRoot.push(`  --clara-type-${kebab}-weight: ${scale.weight};`);
  if (scale.letterSpacing) {
    linesRoot.push(`  --clara-type-${kebab}-tracking: ${scale.letterSpacing};`);
  }
}
linesRoot.push('');

// Focus Tokens (Light defaults)
linesRoot.push('  /* Focus Tokens */');
const lightFocusColor = tokens.focus?.light?.ringColor || tokens.color.brand['600'];
const focusRingWidth = tokens.focus?.ringWidth ?? tokens.focus?.light?.ringWidth ?? 2;
const focusRingOffset = tokens.focus?.ringOffset ?? tokens.focus?.light?.ringOffset ?? 2;
linesRoot.push(`  --focus-ring-color: ${lightFocusColor};`);
linesRoot.push(`  --focus-ring-width: ${focusRingWidth}px;`);
linesRoot.push(`  --focus-ring-offset: ${focusRingOffset}px;`);
linesRoot.push(`  --clara-focus-ring-color: ${lightFocusColor};`);
linesRoot.push(`  --clara-focus-ring-width: ${focusRingWidth}px;`);
linesRoot.push(`  --clara-focus-ring-offset: ${focusRingOffset}px;`);
linesRoot.push('');

// Semantic Light Theme
linesRoot.push('  /* Default Light Theme Semantics */');
for (const [key, val] of Object.entries(tokens.color.neutral.light)) {
  const kebab = toKebabCase(key);
  linesRoot.push(`  --${kebab}: ${val};`);
  if (key === 'canvas') {
    linesRoot.push(`  --canvas-bg: ${val};`);
  }
  const surfaceMatch = key.match(/^surface(\d+)$/);
  if (surfaceMatch) {
    linesRoot.push(`  --surface-${surfaceMatch[1]}: ${val};`);
  }
}
linesRoot.push('');

linesRoot.push(`  --action-primary: ${tokens.color.brand['600']};`);
linesRoot.push(`  --action-primary-hover: ${tokens.color.brand['700']};`);
linesRoot.push(`  --action-primary-pressed: ${tokens.color.brand['800']};`);
linesRoot.push('');

linesRoot.push('  /* Status Light */');
for (const [key, val] of Object.entries(tokens.color.status.light)) {
  linesRoot.push(`  --status-${toKebabCase(key)}: ${val};`);
}
linesRoot.push('');

linesRoot.push('  /* Glass Light */');
linesRoot.push(`  --glass-fill: ${tokens.glass.light.fill};`);
linesRoot.push(`  --glass-fill-strong: ${tokens.glass.light.fillStrong};`);
linesRoot.push(`  --glass-stroke: ${tokens.glass.light.stroke};`);
linesRoot.push(`  --glass-edge: ${tokens.glass.light.edge};`);
linesRoot.push(`  --glass-blur-regular: ${tokens.glass.light.blurRegular}px;`);
linesRoot.push(`  --glass-blur-strong: ${tokens.glass.light.blurStrong}px;`);
linesRoot.push('');

linesRoot.push('  /* Elevation Light */');
for (const [key, val] of Object.entries(tokens.elevation.light)) {
  const num = key.replace('shadow', '');
  linesRoot.push(`  --shadow-${num}: ${val};`);
}

if (tokens.atmosphere?.light) {
  linesRoot.push('');
  linesRoot.push('  /* Light Atmosphere Overrides */');
  for (const [role, val] of Object.entries(tokens.atmosphere.light)) {
    linesRoot.push(`  --atmosphere-${role}: ${val};`);
  }
}

// --- Semantic Dark Theme ---
linesDark.push('  /* Dark Theme Semantics */');
for (const [key, val] of Object.entries(tokens.color.neutral.dark)) {
  const kebab = toKebabCase(key);
  linesDark.push(`  --${kebab}: ${val};`);
  if (key === 'canvas') {
    linesDark.push(`  --canvas-bg: ${val};`);
  }
  const surfaceMatch = key.match(/^surface(\d+)$/);
  if (surfaceMatch) {
    linesDark.push(`  --surface-${surfaceMatch[1]}: ${val};`);
  }
}
linesDark.push('');

linesDark.push(`  --action-primary: ${tokens.color.brand['500']};`);
linesDark.push(`  --action-primary-hover: ${tokens.color.brand['400']};`);
linesDark.push(`  --action-primary-pressed: ${tokens.color.brand['600']};`);
linesDark.push('');

linesDark.push('  /* Status Dark */');
for (const [key, val] of Object.entries(tokens.color.status.dark)) {
  linesDark.push(`  --status-${toKebabCase(key)}: ${val};`);
}
linesDark.push('');

// Dark Focus Tokens
linesDark.push('  /* Focus Tokens (Dark) */');
const darkFocusColor = tokens.focus?.dark?.ringColor || tokens.color.brand['300'];
const darkFocusRingWidth = tokens.focus?.dark?.ringWidth ?? focusRingWidth;
const darkFocusRingOffset = tokens.focus?.dark?.ringOffset ?? focusRingOffset;
linesDark.push(`  --focus-ring-color: ${darkFocusColor};`);
linesDark.push(`  --focus-ring-width: ${darkFocusRingWidth}px;`);
linesDark.push(`  --focus-ring-offset: ${darkFocusRingOffset}px;`);
linesDark.push(`  --clara-focus-ring-color: ${darkFocusColor};`);
linesDark.push(`  --clara-focus-ring-width: ${darkFocusRingWidth}px;`);
linesDark.push(`  --clara-focus-ring-offset: ${darkFocusRingOffset}px;`);
linesDark.push('');

linesDark.push('  /* Glass Dark */');
linesDark.push(`  --glass-fill: ${tokens.glass.dark.fill};`);
linesDark.push(`  --glass-fill-strong: ${tokens.glass.dark.fillStrong};`);
linesDark.push(`  --glass-stroke: ${tokens.glass.dark.stroke};`);
linesDark.push(`  --glass-edge: ${tokens.glass.dark.edge};`);
linesDark.push(`  --glass-blur-regular: ${tokens.glass.dark.blurRegular}px;`);
linesDark.push(`  --glass-blur-strong: ${tokens.glass.dark.blurStrong}px;`);
linesDark.push('');

linesDark.push('  /* Elevation Dark */');
for (const [key, val] of Object.entries(tokens.elevation.dark)) {
  const num = key.replace('shadow', '');
  linesDark.push(`  --shadow-${num}: ${val};`);
}

if (tokens.atmosphere?.dark) {
  linesDark.push('');
  linesDark.push('  /* Dark Atmosphere Overrides */');
  for (const [role, val] of Object.entries(tokens.atmosphere.dark)) {
    linesDark.push(`  --atmosphere-${role}: ${val};`);
  }
}

const css = `${headerComment}
:root {
${linesRoot.join('\n')}
}

[data-theme="dark"],
.dark {
${linesDark.join('\n')}
}
`;

fs.writeFileSync(path.join(__dirname, '../../apps/web/styles/generated/tokens.css'), css);

// ==========================================
// 2. Generate Flutter Dart tokens (clara_tokens.g.dart)
// ==========================================
const dartLines = [];

dartLines.push('  // Brand Azure');
for (const [step, val] of Object.entries(tokens.color.brand)) {
  dartLines.push(`  static const Color brand${step} = ${hexToDartColor(val)};`);
}
dartLines.push('');

dartLines.push('  // Azure Aliases');
for (const [step, val] of Object.entries(azureSource)) {
  dartLines.push(`  static const Color azure${step} = ${hexToDartColor(val)};`);
}
dartLines.push('');

dartLines.push('  // AI Iris (10-step)');
for (const [step, val] of Object.entries(tokens.color.iris)) {
  dartLines.push(`  static const Color iris${step} = ${hexToDartColor(val)};`);
}
dartLines.push('');

dartLines.push('  // Vibrant Clinical Mint (10-step)');
for (const [step, val] of Object.entries(tokens.color.mint)) {
  dartLines.push(`  static const Color mint${step} = ${hexToDartColor(val)};`);
}
dartLines.push('');

dartLines.push('  // Role Accents');
for (const [role, val] of Object.entries(tokens.color.role)) {
  dartLines.push(`  static const Color role${capitalize(role)} = ${hexToDartColor(val)};`);
}
dartLines.push('');

if (tokens.atmosphere) {
  dartLines.push('  // Ambient Atmosphere');
  for (const [role, val] of Object.entries(tokens.atmosphere)) {
    if (typeof val === 'string') {
      dartLines.push(`  static const Color atmosphere${capitalize(role)} = ${hexToDartColor(val)};`);
    }
  }
  if (tokens.atmosphere.light) {
    for (const [role, val] of Object.entries(tokens.atmosphere.light)) {
      dartLines.push(`  static const Color lightAtmosphere${capitalize(role)} = ${hexToDartColor(val)};`);
    }
  }
  if (tokens.atmosphere.dark) {
    for (const [role, val] of Object.entries(tokens.atmosphere.dark)) {
      dartLines.push(`  static const Color darkAtmosphere${capitalize(role)} = ${hexToDartColor(val)};`);
    }
  }
  dartLines.push('');
}

dartLines.push('  // Focus Tokens');
dartLines.push(`  static const double focusRingWidth = ${focusRingWidth}.0;`);
dartLines.push(`  static const double focusRingOffset = ${focusRingOffset}.0;`);
dartLines.push(`  static const Color lightFocusRingColor = ${hexToDartColor(lightFocusColor)};`);
dartLines.push(`  static const Color darkFocusRingColor = ${hexToDartColor(darkFocusColor)};`);
dartLines.push('');

dartLines.push('  // Spacing (4px base)');
for (const [step, val] of Object.entries(tokens.spacing)) {
  dartLines.push(`  static const double space${step} = ${val}.0;`);
}
dartLines.push('');

dartLines.push('  // Radius');
for (const [key, val] of Object.entries(tokens.radius)) {
  dartLines.push(`  static const double radius${capitalize(key)} = ${val}.0;`);
}
dartLines.push('');

dartLines.push('  // Motion Durations');
for (const [key, val] of Object.entries(tokens.motion.duration)) {
  dartLines.push(`  static const Duration motion${capitalize(key)} = Duration(milliseconds: ${val});`);
}
dartLines.push('');

dartLines.push('  // Light Neutrals');
for (const [key, val] of Object.entries(tokens.color.neutral.light)) {
  dartLines.push(`  static const Color light${capitalize(key)} = ${hexToDartColor(val)};`);
}
dartLines.push('');

dartLines.push('  // Dark Neutrals');
for (const [key, val] of Object.entries(tokens.color.neutral.dark)) {
  dartLines.push(`  static const Color dark${capitalize(key)} = ${hexToDartColor(val)};`);
}
dartLines.push('');

dartLines.push('  // Status Light');
for (const [key, val] of Object.entries(tokens.color.status.light)) {
  dartLines.push(`  static const Color lightStatus${capitalize(key)} = ${hexToDartColor(val)};`);
}
dartLines.push('');

dartLines.push('  // Status Dark');
for (const [key, val] of Object.entries(tokens.color.status.dark)) {
  dartLines.push(`  static const Color darkStatus${capitalize(key)} = ${hexToDartColor(val)};`);
}
dartLines.push('');

dartLines.push('  // Glass Light');
dartLines.push(`  static const Color lightGlassFill = ${hexToDartColor(tokens.glass.light.fill)};`);
dartLines.push(`  static const Color lightGlassFillStrong = ${hexToDartColor(tokens.glass.light.fillStrong)};`);
dartLines.push(`  static const Color lightGlassStroke = ${hexToDartColor(tokens.glass.light.stroke)};`);
dartLines.push(`  static const Color lightGlassEdge = ${hexToDartColor(tokens.glass.light.edge)};`);
dartLines.push(`  static const double lightGlassBlurRegular = ${tokens.glass.light.blurRegular}.0;`);
dartLines.push(`  static const double lightGlassBlurStrong = ${tokens.glass.light.blurStrong}.0;`);
dartLines.push('');

dartLines.push('  // Glass Dark');
dartLines.push(`  static const Color darkGlassFill = ${hexToDartColor(tokens.glass.dark.fill)};`);
dartLines.push(`  static const Color darkGlassFillStrong = ${hexToDartColor(tokens.glass.dark.fillStrong)};`);
dartLines.push(`  static const Color darkGlassStroke = ${hexToDartColor(tokens.glass.dark.stroke)};`);
dartLines.push(`  static const Color darkGlassEdge = ${hexToDartColor(tokens.glass.dark.edge)};`);
dartLines.push(`  static const double darkGlassBlurRegular = ${tokens.glass.dark.blurRegular}.0;`);
dartLines.push(`  static const double darkGlassBlurStrong = ${tokens.glass.dark.blurStrong}.0;`);

const dart = `// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by packages/design-tokens/generate.js
// Source Hash: ${tokenHash}
// Version: ${tokens.version}

import 'package:flutter/material.dart';

abstract final class ClaraGeneratedTokens {
${dartLines.join('\n')}
}
`;

fs.writeFileSync(path.join(__dirname, '../../apps/mobile/lib/theme/generated/clara_tokens.g.dart'), dart);

console.log('✅ Generated tokens.css and clara_tokens.g.dart successfully (Hash: ' + tokenHash + ')');
