"""LLM provider clients and Model Gateway v2 for CLARA ML service."""

from __future__ import annotations

from clara_ml.llm.capabilities import ModelCapability, RouteClass
from clara_ml.llm.circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerOpenError,
    CircuitState,
    get_breaker,
    get_llm_circuit_breaker,
    reset_registry,
)
from clara_ml.llm.deepseek_client import DeepSeekClient, DeepSeekResponse
from clara_ml.llm.model_gateway import (
    ModelGateway,
    ModelRunProvenance,
    compute_context_digest,
    get_model_gateway,
)
from clara_ml.llm.model_registry import (
    PRIMARY_MODEL_VERSION,
    ROLLBACK_MODEL_VERSION,
    TASK_CONTRACT_SCHEMA_VERSION,
    TASK_CONTRACTS,
    AsrModelSelection,
    AsrProviderRoute,
    AsrProviderSelection,
    EncoderShadowSelection,
    ModelSelection,
    ModelTask,
    TaskContract,
    build_asr_task_client,
    build_task_client,
    load_task_contracts,
    resolve_asr_model_selection,
    resolve_asr_provider_selection,
    resolve_encoder_shadow_selection,
    resolve_model_selection,
    task_contract,
)
from clara_ml.llm.provider_adapters import (
    CapabilityMismatchError,
    DeepSeekAdapter,
    GatewayAuthenticationError,
    GatewayError,
    GatewayInvalidResponseError,
    GatewayRateLimitError,
    GatewayServiceUnavailableError,
    GatewayTimeoutError,
    ModelMessage,
    ModelProviderAdapter,
    ModelRequest,
    ModelResponse,
    ProbeResult,
    ResolvedRoute,
    UnofficialGeminiGatewayAdapter,
)

__all__ = [
    "PRIMARY_MODEL_VERSION",
    "ROLLBACK_MODEL_VERSION",
    "TASK_CONTRACTS",
    "TASK_CONTRACT_SCHEMA_VERSION",
    "AsrModelSelection",
    "AsrProviderRoute",
    "AsrProviderSelection",
    "CapabilityMismatchError",
    "CircuitBreaker",
    "CircuitBreakerOpenError",
    "CircuitState",
    "DeepSeekAdapter",
    "DeepSeekClient",
    "DeepSeekResponse",
    "EncoderShadowSelection",
    "GatewayAuthenticationError",
    "GatewayError",
    "GatewayInvalidResponseError",
    "GatewayRateLimitError",
    "GatewayServiceUnavailableError",
    "GatewayTimeoutError",
    "ModelCapability",
    "ModelGateway",
    "ModelMessage",
    "ModelProviderAdapter",
    "ModelRequest",
    "ModelResponse",
    "ModelRunProvenance",
    "ModelSelection",
    "ModelTask",
    "ProbeResult",
    "ResolvedRoute",
    "RouteClass",
    "TaskContract",
    "UnofficialGeminiGatewayAdapter",
    "build_asr_task_client",
    "build_task_client",
    "compute_context_digest",
    "get_breaker",
    "get_llm_circuit_breaker",
    "get_model_gateway",
    "load_task_contracts",
    "reset_registry",
    "resolve_asr_model_selection",
    "resolve_asr_provider_selection",
    "resolve_encoder_shadow_selection",
    "resolve_model_selection",
    "task_contract",
]
